### ISSUE TITLE
Commented out functions in nl_params.jl

### ISSUE THREAD

**Issue by odow** [jump-dev/AmplNLWriter.jl#15]
What's the reasoning behind commenting out some of the functions in `nl_params.jl`? (i.e. [min()](https://github.com/JackDunnNZ/AmplNLWriter.jl/blob/master/src/nl_params.jl#L9))

**Comment by JackDunnNZ** [comment]
That dict contains the complete set of .nl functions, with a mapping from the Julia equivalent. The ones that are commented out still have the canonical names from https://ampl.github.io/nlwrite.pdf and haven't yet been mapped into a Julia-compatible form (or tested that it works if the name is the same). 

There's sometimes some differences between the Julia version and the .nl version that needs to be accounted for, e.g. `floor` is a unary function in .nl but the Julia version also has parameters for type, num_digits and base.

`nl_convert.jl` is where we map the more complicated formula back to the elementary .nl operators.

**Comment by odow** [comment]
The reason I ask is that in my model, I have a variable that is the minimum of three linear functions which is currently implemented as:
```
x <= f1(x)
x <= f2(x)
x <= f3(x)
```
however sometimes `x` is not on the surface of those constaints so it should really be:
```
x == min( f1(x), f2(x), f3(x) )
```

Now, if I uncomment the `:min` lines in `nl_params.jl` ([9](https://github.com/JackDunnNZ/AmplNLWriter.jl/blob/master/src/nl_params.jl#L9) and [78](https://github.com/JackDunnNZ/AmplNLWriter.jl/blob/master/src/nl_params.jl#L78)) and plug it into my model. It seems to solve correctly. However, on simple test cases like 
```
maximise:
    min(x, -x, 0.5x-0.25)
s/t:
    -1 <= x <= 1
```
Ipopt gets close but never seems to converge...

Here's the model and resulting .nl file https://gist.github.com/odow/66998c7aab1137e196f7

From what I can tell, the .nl file looks to be built okay. Does this mean its an `Ipopt` issue? Or do I have to change something else in `AmplNLWriter`?

**Comment by JackDunnNZ** [comment]
On face value, the .nl file seems to be built fine, and I just solved it with SCIP, which was nearly instant. Bonmin decided it was too hard and stopped, Ipopt was cycling like you say, and Couenne doesn't do min/max. But I would still think it's a solver problem at this point, the .nl is well formed and SCIP manages. It's just a hard problem?

I think the reason that min/max were still commented out is because of there are multiple ways to get there from Julia, e.g.

    min(x, -x, 0.5x-0.25)
    minimum([x, -x, 0.5x-0.25])

The first works with the changes you made, but the second should be converted into the first. So it's actually probably okay for us to enable `min/max` for now, just they will only work for a simple call like yours.
