### ISSUE TITLE
Result index of attribute MathOptInterface.VariablePrimal(1) out of bounds.

### ISSUE THREAD

**Issue by lauinger** [jump-dev/AmplNLWriter.jl#159]
Hello,

I tried Bonmin and Couenne with AmplNLWriter on very simple problems. I find that:
- Bonmin works fine on NLPs, but Couenne may fail depending on the starting point.
- For 1 dimensional ILPs, Bonmin and Couenne both work fine.
- For multi-dimensional ILPs, Couenne works fine but Bonmin fails, apparently because of an Ipopt error ('_Ipopt exited with error code -11 Invalid problem definition_'), which is weird because there should be no need to call Ipopt for ILPs. The final error is '_Result index of attribute MathOptInterface.VariablePrimal(1) out of bounds_.'
- For MILPs, Couenne works fine but Bonmin fails with '_Assertion failed: isNlpFeasible(minlp, primalTolerance), file BonHeuristicDiveMIP.cpp, line 133'_. The final error is again '_Result index of attribute MathOptInterface.VariablePrimal(1) out of bounds_.' 
- For INLPs, Couenne fails with again the same error message '_Result index of attribute MathOptInterface.VariablePrimal(1) out of bounds_.' 

Juniper with Ipopt as nonlinear solver and Cbc as MIP solver (same as for Bonmin) manages to solve all testcases without problems.

I attach a jupyter notebook `bonmin-couenne-test` with the testcases for Bonmin and Couenne and a notebook `juniper-test` with the Juniper implementation in the file `test-cases.zip`.
[test-cases.zip](https://github.com/jump-dev/AmplNLWriter.jl/files/9882258/test-cases.zip)

Do you have any idea of where this behavior is coming from?

Here is how I import the julia libraries and set up Bonmin and Couenne:
```
using JuMP, AmplNLWriter, Bonmin_jll, Couenne_jll
model = Model(() -> AmplNLWriter.Optimizer(Bonmin_jll.amplexe))
# or for Couenne:
# model = Model(() -> AmplNLWriter.Optimizer(Couenne_jll.amplexe))
```

**Comment by odow** [comment]
Before accessing the solution via `value`, you need to check if a solution is present by looking at `termination_status(model)` and `primal_status(model)`. A handy tool is `solution_summary(model)`.

You should know that Bonmin and Couenne are okay open-source solvers, but they are not very robust and are easy to break.

As one example:

```Julia
# multi-dimensional ILP
model = Model(() -> AmplNLWriter.Optimizer(Bonmin_jll.amplexe))
# model = Model(() -> AmplNLWriter.Optimizer(Couenne_jll.amplexe))
l = [0.5, 0]
@variable(model, x[i = 1:2] >= l[i], Int)
@objective(model, Min, x[1] + x[2])
print(model)
optimize!(model)
solution_summary(model)
# println(value.(x))
# print(objective_value(model))
```

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/8177701/198377405-86e093cb-0796-469b-a301-6da593e938ed.png">

the problem is a fractional lower bound

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/8177701/198377468-fa4c8080-52d0-43b3-8a4e-5dcff4fb1716.png">

I get that this is quite painful, but it's a quirk of the solver, not in JuMP or AmplNLWriter.

If you want to keep discussing, please make a post on the community forum, https://discourse.julialang.org/c/domain/opt/13. Many more people read the forum and it may help others in future. We try to keep the GitHub issues for bug reports.

**Comment by lauinger** [comment]
Thank you for the fast reply! I will run some more tests with non-fractional lower bounds, refine my test cases, and then post something on the community forum. Thank you for pointing me there.
