### ISSUE TITLE
I use Solver of AmplNLWriter with some errors.

### ISSUE THREAD

**Issue by JunWang-JUST** [jump-dev/AmplNLWriter.jl#183]
```
* Solver : AmplNLWriter

* Status
  Result count       : 0
  Termination status : OTHER_ERROR
  Message from the solver:
  "Error calling the solver. Failed with: SystemError("opening file \"C:\\\\Users\\\\USER_NAME\\\\AppData\\\\Local\\\\Temp\\\\jl_FlGPBt\\\\model.sol\"", 2, nothing)"

* Candidate solution (result #1)
  Primal status      : NO_SOLUTION
  Dual status        : NO_SOLUTION

* Work counters
  Solve time (sec)   : 1.25000e-01
```
```
@show value(x)
ERROR: Result index of attribute MathOptInterface.VariablePrimal(1) out of bounds. There are currently 0 solution(s) in the model.
```

**Comment by odow** [comment]
The solver did not produce a solution.

Do you have a reproducible example?

**Comment by odow** [comment]
Since the missing sol file is a reasonably common cause, we could add a better error message:
https://github.com/jump-dev/AmplNLWriter.jl/blob/4346406c90794df56c900be4fc1f47ad12abc777/src/AmplNLWriter.jl#L289-L296

**Comment by odow** [comment]
I've improved the error message in #184.

It typically means that your problem was infeasible, or that there was some other problem with the formulation.

If you can supply a reproducible example, please make a post on our community forum https://discourse.julialang.org/c/domain/opt/13 and we can chat over there  :smile:
