### ISSUE TITLE
Solver Parameter Consistency

### ISSUE THREAD

**Issue by ccoffrin** [jump-dev/AmplNLWriter.jl#44]
In most of the other JuMP solvers parameters are input as keyword arguments like so,

`solverName(param1 = val, param2 = val, ...)`

In the NL writer we have to give parameters as an array of strings, like so,

`solverName(["solver.param1 = val", "solver.param2 = val", ...])`

It seems to me that it is fairly easy to re-write keyword arguments into this string-array format.  If so, why not make these solver's parameter API similar to other solvers in JuMP?

**Comment by mlubin** [comment]
The dots don't translate to Julia syntax, unfortunately. Previous discussion: https://github.com/JuliaOpt/AmplNLWriter.jl/issues/2

**Comment by ccoffrin** [comment]
Yes I agree that needs to be addressed.  What I had did in our code was like this,

When you are calling a specific solver, say `BonminNLSolver(...)`, the parameter prefix in the vast majority of cases will be "bonmin", so if you give me a keyword argument like `bb_log_level=0`, I'll translate it into a string `"bonmin.bb_log_level=0"`.  

The only remaining issue would be how to get around this default prefix.  For that I would try to make the function support var-args of strings.  So I could write something like,

`BonminNLSolver("ipopt.tol=1e-2"; bb_log_level=0)`

or 

`BonminNLSolver("bonmin.bb_log_level=0", "ipopt.tol=1e-2")`

as one prefers.

**Comment by mlubin** [comment]
Var-args of strings seems like a pretty decent syntax

**Comment by JackDunnNZ** [comment]
Yes, I agree that the var-args of strings is a nice way of doing it. I'm hesitant about including any notion of default prefixes because there are still options in the COIN solvers that aren't prefixed. As per #2 we also wanted to stay away from any solver-specific behaviour wherever possible.

What do you think about offering kwarg options like other solvers and then also offer the var-args of strings as a fallback for those solvers that need dots in the parameter names. It's kind of messy to have two ways of supplying options, but it would be nice to be consistent with everything and is a shame to lose that just because the COIN solvers are difficult? Basically what you suggested @ccoffrin but without any automatic prefix addition:

    BonminNLSolver("ipopt.tol=1e-2", "bonmin.bb_log_level=0"; wantsol=1)

**Comment by ccoffrin** [comment]
Looks good to me!

**Comment by ccoffrin** [comment]
@odow, will this become moot with the `optimizer_with_attirbutes` change?

**Comment by odow** [comment]
Yes, but I guess we need to support `RawParameter`.
